### ISSUE TITLE
FileNotFoundError and KeyinFileError, when running efficiency gen script on glacier  

### ISSUE THREAD

**Issue by ZishuoYang** [umd-lhcb/pidcalib2#2]
When I attempted to generate new efficiency histograms today, the same script working last week failed. The same errors were reproduced with the example `rdx-run2-ubdt.sh` script on `K` sample (not `Mu_nopt`). It seems that the sample files have changed, perhaps recently related to updating uBDT? @yipengsun 

For the Kaon magnet down sample:
```
[I 220804 12:47:37 make_eff_hists:182] Running PIDCalib2 make_eff_hists with the following config:
[I 220804 12:47:37 utils:117] ===============
[I 220804 12:47:37 utils:120] sample         : Turbo16
[I 220804 12:47:37 utils:120] magnet         : down
[I 220804 12:47:37 utils:120] particle       : K
[I 220804 12:47:37 utils:120] pid_cuts       : ['DLLmu>2.0&DLLe<1.0&IsMuon==1.0&UBDT>0.25']
[I 220804 12:47:37 utils:120] bin_vars       : ['Brunel_P', 'Brunel_ETA', 'nTracks_Brunel']
[I 220804 12:47:37 utils:120] output_dir     : pidcalib_output
[I 220804 12:47:37 utils:120] verbose        : False
[I 220804 12:47:37 utils:120] version        : N/A
[I 220804 12:47:37 utils:121] ===============
[W 220804 12:47:37 make_eff_hists:186] No --cut specified. Cuts on PID samples should match your sample cuts.
[I 220804 12:47:37 utils:461] Branches to be read: {'sWeight': 'probe_sWeight', 'DLLmu': 'probe_PIDmu', 'DLLe': 'probe_PIDe', 'IsMuon': 'probe_isMuon', 'UBDT': 'probe_UBDT', 'Brunel_P': 'probe_Brunel_P', 'Brunel_ETA': 'probe_Brunel_ETA', 'nTracks_Brunel': 'nTracks_Brunel'}
[I 220804 12:47:37 utils:462] 164 calibration files from EOS will be processed
Traceback (most recent call last):
  File "/nix/store/0d3v4mnl4brm8rcl40dbsdy1xh3vz8ip-python3.8-pidcalib2-1.0.6-umd/lib/python3.8/site-packages/pidcalib2/pid_data.py", line 271, in root_to_dataframe
    tree = root_file[tree_name]
  File "/nix/store/cdl9600yh6pb5fb9406kxq88xxrmmwi2-python3.8-uproot-4.2.3/lib/python3.8/site-packages/uproot/reading.py", line 2079, in __getitem__
    step = step[item]
  File "/nix/store/cdl9600yh6pb5fb9406kxq88xxrmmwi2-python3.8-uproot-4.2.3/lib/python3.8/site-packages/uproot/reading.py", line 2096, in __getitem__
    return self.key(where).get()
  File "/nix/store/cdl9600yh6pb5fb9406kxq88xxrmmwi2-python3.8-uproot-4.2.3/lib/python3.8/site-packages/uproot/reading.py", line 2046, in key
    raise uproot.KeyInFileError(
uproot.exceptions.KeyInFileError: not found: 'DSt_KPTuple' (with any cycle number)

    Available keys: 'DSt_PiMTuple;1', 'DSt_PiMTuple/DecayTree;1'

in file /home/public/pidcalib_ntuples/merged/KPiMu-2016-MagDown/00152077_00000080_1.pidcalib.root

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/0d3v4mnl4brm8rcl40dbsdy1xh3vz8ip-python3.8-pidcalib2-1.0.6-umd/bin/.pidcalib2.make_eff_hists-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/0d3v4mnl4brm8rcl40dbsdy1xh3vz8ip-python3.8-pidcalib2-1.0.6-umd/lib/python3.8/site-packages/pidcalib2/make_eff_hists.py", line 228, in main
    make_eff_hists(config)
  File "/nix/store/0d3v4mnl4brm8rcl40dbsdy1xh3vz8ip-python3.8-pidcalib2-1.0.6-umd/lib/python3.8/site-packages/pidcalib2/make_eff_hists.py", line 202, in make_eff_hists
    hists_list = utils.create_histograms(config)
  File "/nix/store/0d3v4mnl4brm8rcl40dbsdy1xh3vz8ip-python3.8-pidcalib2-1.0.6-umd/lib/python3.8/site-packages/pidcalib2/utils.py", line 487, in create_histograms
    df = pid_data.root_to_dataframe(
  File "/nix/store/0d3v4mnl4brm8rcl40dbsdy1xh3vz8ip-python3.8-pidcalib2-1.0.6-umd/lib/python3.8/site-packages/pidcalib2/pid_data.py", line 278, in root_to_dataframe
    if var in tree.keys():  # type: ignore
AttributeError: 'NoneType' object has no attribute 'keys'
```

For the Kaon magnet up sample:
``` 
./rdx-run2-ubdt.sh
[I 220804 12:47:36 make_eff_hists:182] Running PIDCalib2 make_eff_hists with the following config:
[I 220804 12:47:36 utils:117] ===============
[I 220804 12:47:36 utils:120] sample         : Turbo16
[I 220804 12:47:36 utils:120] magnet         : up
[I 220804 12:47:36 utils:120] particle       : K
[I 220804 12:47:36 utils:120] pid_cuts       : ['DLLmu>2.0&DLLe<1.0&IsMuon==1.0&UBDT>0.25']
[I 220804 12:47:36 utils:120] bin_vars       : ['Brunel_P', 'Brunel_ETA', 'nTracks_Brunel']
[I 220804 12:47:36 utils:120] output_dir     : pidcalib_output
[I 220804 12:47:36 utils:120] verbose        : False
[I 220804 12:47:36 utils:120] version        : N/A
[I 220804 12:47:36 utils:121] ===============
[W 220804 12:47:36 make_eff_hists:186] No --cut specified. Cuts on PID samples should match your sample cuts.
[I 220804 12:47:36 utils:461] Branches to be read: {'sWeight': 'probe_sWeight', 'DLLmu': 'probe_PIDmu', 'DLLe': 'probe_PIDe', 'IsMuon': 'probe_isMuon', 'UBDT': 'probe_UBDT', 'Brunel_P': 'probe_Brunel_P', 'Brunel_ETA': 'probe_Brunel_ETA', 'nTracks_Brunel': 'nTracks_Brunel'}
[I 220804 12:47:36 utils:462] 126 calibration files from EOS will be processed
Traceback (most recent call last):
  File "/nix/store/cdl9600yh6pb5fb9406kxq88xxrmmwi2-python3.8-uproot-4.2.3/lib/python3.8/site-packages/uproot/source/file.py", line 112, in _open
    self._file = numpy.memmap(self._file_path, dtype=self._dtype, mode="r")
  File "/nix/store/77yx9bddzjdh4m5akncd5ihvdpgdpw4p-python3.8-numpy-1.21.5/lib/python3.8/site-packages/numpy/core/memmap.py", line 228, in __new__
    f_ctx = open(os_fspath(filename), ('r' if mode == 'c' else mode)+'b')
FileNotFoundError: [Errno 2] No such file or directory: '/home/public/pidcalib_ntuples/merged/KPiMu-2016-MagUp/00152079_00000114_1.pidcalib.root'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/cdl9600yh6pb5fb9406kxq88xxrmmwi2-python3.8-uproot-4.2.3/lib/python3.8/site-packages/uproot/source/file.py", line 36, in __init__
    self._file = open(self._file_path, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/public/pidcalib_ntuples/merged/KPiMu-2016-MagUp/00152079_00000114_1.pidcalib.root'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/0d3v4mnl4brm8rcl40dbsdy1xh3vz8ip-python3.8-pidcalib2-1.0.6-umd/bin/.pidcalib2.make_eff_hists-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/0d3v4mnl4brm8rcl40dbsdy1xh3vz8ip-python3.8-pidcalib2-1.0.6-umd/lib/python3.8/site-packages/pidcalib2/make_eff_hists.py", line 228, in main
    make_eff_hists(config)
  File "/nix/store/0d3v4mnl4brm8rcl40dbsdy1xh3vz8ip-python3.8-pidcalib2-1.0.6-umd/lib/python3.8/site-packages/pidcalib2/make_eff_hists.py", line 202, in make_eff_hists
    hists_list = utils.create_histograms(config)
  File "/nix/store/0d3v4mnl4brm8rcl40dbsdy1xh3vz8ip-python3.8-pidcalib2-1.0.6-umd/lib/python3.8/site-packages/pidcalib2/utils.py", line 487, in create_histograms
    df = pid_data.root_to_dataframe(
  File "/nix/store/0d3v4mnl4brm8rcl40dbsdy1xh3vz8ip-python3.8-pidcalib2-1.0.6-umd/lib/python3.8/site-packages/pidcalib2/pid_data.py", line 248, in root_to_dataframe
    root_file = uproot.open(path)
  File "/nix/store/cdl9600yh6pb5fb9406kxq88xxrmmwi2-python3.8-uproot-4.2.3/lib/python3.8/site-packages/uproot/reading.py", line 141, in open
    file = ReadOnlyFile(
  File "/nix/store/cdl9600yh6pb5fb9406kxq88xxrmmwi2-python3.8-uproot-4.2.3/lib/python3.8/site-packages/uproot/reading.py", line 580, in __init__
    self._source = Source(
  File "/nix/store/cdl9600yh6pb5fb9406kxq88xxrmmwi2-python3.8-uproot-4.2.3/lib/python3.8/site-packages/uproot/source/file.py", line 108, in __init__
    self._open()
  File "/nix/store/cdl9600yh6pb5fb9406kxq88xxrmmwi2-python3.8-uproot-4.2.3/lib/python3.8/site-packages/uproot/source/file.py", line 118, in _open
    self._fallback = uproot.source.file.MultithreadedFileSource(
  File "/nix/store/cdl9600yh6pb5fb9406kxq88xxrmmwi2-python3.8-uproot-4.2.3/lib/python3.8/site-packages/uproot/source/file.py", line 250, in __init__
    self._open()
  File "/nix/store/cdl9600yh6pb5fb9406kxq88xxrmmwi2-python3.8-uproot-4.2.3/lib/python3.8/site-packages/uproot/source/file.py", line 254, in _open
    [FileResource(self._file_path) for x in range(self._num_workers)]
  File "/nix/store/cdl9600yh6pb5fb9406kxq88xxrmmwi2-python3.8-uproot-4.2.3/lib/python3.8/site-packages/uproot/source/file.py", line 254, in <listcomp>
    [FileResource(self._file_path) for x in range(self._num_workers)]
  File "/nix/store/cdl9600yh6pb5fb9406kxq88xxrmmwi2-python3.8-uproot-4.2.3/lib/python3.8/site-packages/uproot/source/file.py", line 38, in __init__
    raise uproot._util._file_not_found(file_path)
FileNotFoundError: file not found

    '/home/public/pidcalib_ntuples/merged/KPiMu-2016-MagUp/00152079_00000114_1.pidcalib.root'

Files may be specified as:
   * str/bytes: relative or absolute filesystem path or URL, without any colons
         other than Windows drive letter or URL schema.
         Examples: "rel/file.root", "C:\abs\file.root", "http://where/what.root"
   * str/bytes: same with an object-within-ROOT path, separated by a colon.
         Example: "rel/file.root:tdirectory/ttree"
   * pathlib.Path: always interpreted as a filesystem path or URL only (no
         object-within-ROOT path), regardless of whether there are any colons.
         Examples: Path("rel:/file.root"), Path("/abs/path:stuff.root")

Functions that accept many files (uproot.iterate, etc.) also allow:
   * glob syntax in str/bytes and pathlib.Path.
         Examples: Path("rel/*.root"), "/abs/*.root:tdirectory/ttree"
   * dict: keys are filesystem paths, values are objects-within-ROOT paths.
         Example: {"/data_v1/*.root": "ttree_v1", "/data_v2/*.root": "ttree_v2"}
   * already-open TTree objects.
   * iterables of the above.
```

**Comment by ZishuoYang** [comment]
Old sample files have been moved while uBDT update is still going on, so this is expected then
